### PR TITLE
chore: let dependencies as optional

### PR DESCRIPTION
**Pull request by deroldo**
## Objective
Evitar que as dependências da biblioteca estão conflitando com as dependências do projeto que faz uso dela.

## Proposed changes
Deixar as dependências da biblioteca opcional, dessa forma evitando conflitos com as demais bibliotecas  do projeto que a utilizar.

### CODE REVIEW

**Comment by willbank-platforms** [comment]
Atlantis commands can't be run on fork pull requests. To enable, set --allow-fork-prs  or, to disable this message, set --silence-fork-pr-errors

**Comment by willbank-platforms** [comment]
Atlantis commands can't be run on fork pull requests. To enable, set --allow-fork-prs  or, to disable this message, set --silence-fork-pr-errors

**Comment by willbank-platforms** [comment]
```
Error parsing command: EOF found when expecting closing quote
```

**Comment by willbank-platforms** [comment]
```
Error parsing command: EOF found when expecting closing quote
```

**Comment by willbank-platforms** [comment]
```
Error parsing command: EOF found when expecting closing quote
```

**Comment by willbank-platforms** [comment]
```
Error parsing command: EOF found when expecting closing quote
```

**Comment by deroldo** [comment]
Change origin branch to be able to commit on main branch on fork without change PR

**Pull request closed without merging**
